### ISSUE TITLE
Download examples has 404 links

### ISSUE THREAD

**Issue by jarmitage** [ideoforms/signalflow#115]
```py
Downloading examples to: examples
 - Downloaded: audio-through-example.py
 - Downloaded: buffer-play-example.py
 - Downloaded: chaotic-feedback-example.py
 - Downloaded: euclidean-rhythm-example.py
 - Downloaded: granulation-example.py
 - Downloaded: hello-world-example.py
 - Downloaded: karplus-strong-example.py
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File ".../__main__.py", line 8, in <module>
    signalflow_examples.download_examples()
  File "../python3.11/site-packages/signalflow_examples/signalflow_examples.py", line 55, in download_examples
    _download_files_from_url(url_prefix, examples, output_directory)
  File "../python3.11/site-packages/signalflow_examples/signalflow_examples.py", line 23, in _download_files_from_url
    urllib.request.urlretrieve(url, output_path)
  File "../python3.11/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "../python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "../python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "../python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "../python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "../python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by ideoforms** [comment]
Thanks for the spot @jarmitage, looks like I deleted an example but didn't update this script. Will add an automated test for this :)
